### ISSUE TITLE
【功能需求】支持其他期刊网页版，参考文献是超链接网址的 或参考文献，最后附有doi.org/xxxxxxxxxx

### ISSUE THREAD

**Issue by aiyou9** [Xtdzs/Zotero-Pagewise-Import-Tool#2]
https://pubs.acs.org/doi/10.1021/np200722w   
acs杂志社主页，这种附有谷歌搜索网址中有doi的

```
https://pubs.acs.org/action/getFTRLinkout?url=http%3A%2F%2Fscholar.google.com%2Fscholar%3Fhl%3Den%26q%3DClark%252C%2BR.%2BJ.%253B%2BDaly%252C%2BN.%2BL.%253B%2BCraik%252C%2BD.%2BJ.Biochem.%2BJ.%2B2006%252C%2B394%252C%2B85%25E2%2580%259393&doi=10.1021%2Fnp200722w&doiOfLink=10.1042%2FBJ20051691&linkType=gs&linkLocation=Reference&linkSource=FULL_TEXT
````

**Comment by Xtdzs** [comment]
您好，我尝试用zotero connector抓取asc搜索页以及google scholar中内容发现并没有不可加入到本地zotero文库中的情况。不知我是否理解错您的意思了。（另外，zotero connector爬取nature搜索页文章时有严重缺失现象，代码已经写好，过几天准备push上去）

**Comment by aiyou9** [comment]
> 您好，我尝试用zotero connector抓取asc搜索页以及google scholar中内容发现并没有不可加入到本地zotero文库中的情况。不知我是否理解错您的意思了。（另外，zotero connector爬取nature搜索页文章时有严重缺失现象，代码已经写好，过几天准备push上去）

抱歉，我没说清楚，我的意思是爬取单篇论文的参考文献，比如上面那个文献，zotero只能拉取当前论文，而不能识别参考文献，
![image](https://github.com/Xtdzs/Zotero-Pagewise-Import-Tool/assets/15712822/8592ab26-6cff-401e-bde2-4782ec407ad7)
 
scite的浏览器插件有做到这个  https://scite.ai/

https://chromewebstore.google.com/detail/scite/homifejhmckachdikhkgomachelakohh

![image](https://github.com/Xtdzs/Zotero-Pagewise-Import-Tool/assets/15712822/38a6fc70-8ad3-4c8b-9b75-1af62079626b)

**Comment by aiyou9** [comment]
zotero另外一个插件，zotero reference https://github.com/MuiseDestiny/zotero-reference  有对pdf文末的参考文献，进行探嗅，并加入zotero的文献条目下的参考文献列表

**Comment by Xtdzs** [comment]
好的，我明白了。这个提议非常有意义，我会尝试解决。

**Comment by aiyou9** [comment]
还有一种情况，是在文献数据库的层面，可以给出一篇文献的参考文献列表，可惜大部分都是收费的功能。但是开源期刊的增多，这种付费的情况，会越来越小，这个功能还是有价值的

**Comment by Xtdzs** [comment]
您好，最新的版本已经实现了acs中导入引文的功能。我将开放一个讨论区以了解更多需求网站。

**Comment by aiyou9** [comment]
> 您好，最新的版本已经实现了acs中导入引文的功能。我将开放一个讨论区以了解更多需求网站。


讨论区 ➡️ 
Import Functionality Discussion Hub: Let's Focus on More Import Needs! #3
